name: cralwer

on:
  push:
    branches: [main]
  
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: test
      env:
        github_token: ${{ secrets.GITHUBTOKEN }}
        telegram_token: ${{ secrets.TELEGRAMTOKEN }}
        my_id: ${{ secrets.ID }}
        my_password: ${{ secrets.PASSWORD }}
      run: |
        python cralwer.py
