name: cralwer

on:
  push:
    branches: [main]
  
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: test1
      env:
        github_token: ${{ secrets.GITHUBTOKEN }}
        telegram_token: ${{ secrets.TELEGRAMTOKEN }}
        my_id: ${{ secrets.ID }}
        my_password: ${{ secrets.PASSWORD }}
      run: |
        python cralwer.py
    - name: Commits
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -a news.json
        git commit -m "Auto - romove with Crawling" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: 'main'
        github_token: ${{ secrets.GITHUBTOKEN }}
